### GET FOR EVERYONE
GET http://localhost:8000/posts_visible

### SERVER TEST
GET http://localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0OTU2NjQsImV4cCI6MTU5NTU4MjA2NH0.bTyBP5GIUOdJgoPYcz4XgiotTNlKsBzNZBwmHUIC8GA

# ===== POSTS ===== #

### GET ALL POSTS
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0OTU2NjQsImV4cCI6MTU5NTU4MjA2NH0.bTyBP5GIUOdJgoPYcz4XgiotTNlKsBzNZBwmHUIC8GA
### GET A POST BY ID
GET http://localhost:8000/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0OTU2NjQsImV4cCI6MTU5NTU4MjA2NH0.bTyBP5GIUOdJgoPYcz4XgiotTNlKsBzNZBwmHUIC8GA


### POST A POST
POST http://localhost:8000/posts
Content-Type: application/json

{
    "title": "bbbbbbbbbbbbbb",
    "description": "This is bbbbbbbbbbbbbb",
    "media": "img",
    "link": "http://localhost:8000"
}

### UPDATE A POST BY ID
PUT http://localhost:8000/posts/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0OTU2NjQsImV4cCI6MTU5NTU4MjA2NH0.bTyBP5GIUOdJgoPYcz4XgiotTNlKsBzNZBwmHUIC8GA
Content-Type: application/json

{
    "title": "aaaAAAAA",
    "description": "bBBBBBB",
    "media": "aaaaaaa",
    "link": "aaaaaaa"
}

### DELETE A POST BY ID
DELETE http://localhost:8000/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU1MDA3OTksImV4cCI6MTU5NTU4NzE5OX0.-3pjHxLE-lkunm0MIFMoA4JsxIcI0TSFiO2fc-7evc4

# ===== LANGUAGES ===== #

### GET ALL LANGUAGES
GET http://localhost:8000/languages

### GET A LANGUAGE BY ID
GET http://localhost:8000/languages/1

### POST A LANGUAGE
POST http://localhost:8000/languages
Content-Type: application/json

{
    "name": "bbbbbbbbbbbbbb",
    "media": "img"
}

### UPDATE A LANGUAGE BY ID
PUT http://localhost:8000/languages/4
Content-Type: application/json

{
    "name": "ccccccccccc",
    "media": "img"
}

### DELETE A LANGUAGE BY ID
DELETE http://localhost:8000/languages/4

# ===== USER ===== #

### POST - REGISTER
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "username": "brian",
    "password": "secret"
}

### POST - LOGIN
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "username": "brian",
    "password": "secret"
}

###################################
###################################

### GET ALL POSTS AND ALL LANGUAGES
GET http://localhost:8000/posts/languages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0OTU2NjQsImV4cCI6MTU5NTU4MjA2NH0.bTyBP5GIUOdJgoPYcz4XgiotTNlKsBzNZBwmHUIC8GA

### POST A POST AND LANGUAGES
POST http://localhost:8000/posts/languages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU0OTU2NjQsImV4cCI6MTU5NTU4MjA2NH0.bTyBP5GIUOdJgoPYcz4XgiotTNlKsBzNZBwmHUIC8GA
Content-Type: application/json

{
    "title": "bbbbbbbbbbbbbb",
    "description": "This is bbbbbbbbbbbbbb",
    "media": "img",
    "link": "http://localhost:8000",
    "name": "test,"
}

###################################
###################################